### ISSUE TITLE
Add `--set-timeout` flag

### ISSUE THREAD

**Issue by sacha-l** [hack-ink/subalfred#197]
It would be useful to add a timeout flag for utilities other than the `export-state` command. Right now I'm tying to run:

`subalfred get runtime-upgrade-block 9100 --uri wss://rpc.polkadot.io -lsubalfred::core::node`

but keep getting `Error: deadline has elapsed` (probably because my internet connection isn't great atm). 

Also, we should have some mention of the `timeout` feature somewhere. Happy to help on this if it makes sense @AurevoirXavier.

**Comment by AurevoirXavier** [comment]
Thanks for the advice.

---

I write my idea here for future review.

Make the `timeout` to be a shared param to avoid defining it multiple times.
