### ISSUE TITLE
Update crates.io

### ISSUE THREAD

**Issue by binsta** [hack-ink/subalfred#233]
`$ cargo install subalfred`
    Updating crates.io index
error: could not find `subalfred` in registry `crates-io` with version `*`

**Comment by AurevoirXavier** [comment]
Thanks for the issues.

I plan to publish this to crates.io on  0.9.0.

Currently, the version is 0.9.0-rc12.

**Comment by AurevoirXavier** [comment]
> `$ cargo install subalfred` Updating crates.io index error: could not find `subalfred` in registry `crates-io` with version `*`

v0.9.0-rc13 was released.
