### ISSUE TITLE
Subalfred can't decode `Kusama` keys

### ISSUE THREAD

**Issue by Garandor** [hack-ink/subalfred#378]
```
❯ subalfred --version 
subalfred 0.9.0-crates.io-x86_64-apple-darwin
❯ subalfred key 5G9z8Ttoo7892VqBHiSWCbnd2aEdH8noJLqZ4HFMzMVNhvgP --list-all | grep kusama
kusama GfbnnEgRU94n9ed4RFZ6Z9dBAWs5obykigJSwXKU9hsT2uU
sora_kusama_para oFFkmbGShjgXYrvYaD3EymDYUzWEdJvLKxjKSHo1DwqLN5eiM
❯ subalfred key GfbnnEgRU94n9ed4RFZ6Z9dBAWs5obykigJSwXKU9hsT2uU
Error: [core::ss58] invalid address, "GfbnnEgRU94n9ed4RFZ6Z9dBAWs5obykigJSwXKU9hsT2uU"
```
key taken from https://github.com/hack-ink/subalfred/blob/067a4a722c869ef6c6cb3da1497e8718c878532d/doc/src/user/cli/key.md#option-list-all

**Comment by AurevoirXavier** [comment]
> ```
> ❯ subalfred --version 
> subalfred 0.9.0-crates.io-x86_64-apple-darwin
> ❯ subalfred key 5G9z8Ttoo7892VqBHiSWCbnd2aEdH8noJLqZ4HFMzMVNhvgP --list-all | grep kusama
> kusama GfbnnEgRU94n9ed4RFZ6Z9dBAWs5obykigJSwXKU9hsT2uU
> sora_kusama_para oFFkmbGShjgXYrvYaD3EymDYUzWEdJvLKxjKSHo1DwqLN5eiM
> ❯ subalfred key GfbnnEgRU94n9ed4RFZ6Z9dBAWs5obykigJSwXKU9hsT2uU
> Error: [core::ss58] invalid address, "GfbnnEgRU94n9ed4RFZ6Z9dBAWs5obykigJSwXKU9hsT2uU"
> ```
> 
> 
>      
>   
> 
> key taken from https://github.com/hack-ink/subalfred/blob/067a4a722c869ef6c6cb3da1497e8718c878532d/doc/src/user/cli/key.md#option-list-all

Fixed. You could build it from the main branch now.

I'll release a new version later.
