### ISSUE TITLE
Feature request: Check non-dev dependencies for `default-features` toggled off

### ISSUE THREAD

**Issue by wischli** [hack-ink/subalfred#482]
First of all, I would like to give thanks to you for this great tool. Been mainly using the `check features` feature which came in super nifty when `try-runtime` feats became more restrictive. 

Anyway, I was wondering whether it would be much overhead to add a new feature which just lists/checks non develop dependencies for `default-features` toggled off. It still happens way too often that some dependency is loaded with `std` not turned off by mistake. As you know, finding that needle in the hay can be super fiddly. I envision `subalfred` to once again come to the rescue for such cases.

As an example, we imported a dependency `example-dep` in non-dev environment and added all missing features `example-dep/std`, `example-dep/runtime-benchmarks` as well as `example-dep/try-runtime` derived via `subalfed` as part of a Substrate update. However, by mistake the `example-dep` dependency was configured with `default-features = true` which we only found after digging through all 50 Cargo.toml diffs.

**Comment by AurevoirXavier** [comment]
I have found a solution for this issue. The updated version will be published within the next few days, I believe.

**Comment by AurevoirXavier** [comment]
https://github.com/hack-ink/cargo-featalign @wischli
