### ISSUE TITLE
Support Stable Toolchain

### ISSUE THREAD

**Issue by flipchan** [hack-ink/subalfred#79]
Hey,
This is a great project but it only seems to be possible to run it with `+nightly`, would it be possible that you can rewrite the threading logic so it can build with `cargo build --release`. Also this project should be published on crates.io so users can download it with cargo install

**Comment by AurevoirXavier** [comment]
I'll take a look at this tonight.

**Comment by AurevoirXavier** [comment]
I'm afraid not.
Currently, the CLI part heavily depends on [concat_idents](https://doc.rust-lang.org/std/macro.concat_idents.html).
Once #80 is done, I'll finish this ASAP.

**Comment by flipchan** [comment]
> I'm afraid not. Currently, the CLI part heavily depends on [concat_idents](https://doc.rust-lang.org/std/macro.concat_idents.html). Once #80 is done, I'll finish this ASAP.

Great, would be nice if it supported stable and could be on crates.io

**Comment by AurevoirXavier** [comment]
> Great, would be nice if it supported stable and could be on crates.io

Done. But I'm not sure if I should push this to crates.io. It's still in RC version.
